// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user_service.proto

package user_servicePB

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _user_service_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on User with the rules defined in the proto
// definition for this message. If any rules are violated, the first error
// encountered is returned, or nil if there are no violations.
func (m *User) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on User with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in UserMultiError, or nil if none found.
func (m *User) ValidateAll() error {
	return m.validate(true)
}

func (m *User) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = UserValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserName()); l < 2 || l > 128 {
		err := UserValidationError{
			field:  "UserName",
			reason: "value length must be between 2 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_User_UserName_Pattern.MatchString(m.GetUserName()) {
		err := UserValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserPassword()); l < 8 || l > 72 {
		err := UserValidationError{
			field:  "UserPassword",
			reason: "value length must be between 8 and 72 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_User_UserPassword_Pattern.MatchString(m.GetUserPassword()) {
		err := UserValidationError{
			field:  "UserPassword",
			reason: "value does not match regex pattern \"^[\\\\x21-\\\\x7E]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _User_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := UserValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := UserRoles_name[int32(m.GetUserRole())]; !ok {
		err := UserValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserMultiError(errors)
	}

	return nil
}

func (m *User) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UserMultiError is an error wrapping multiple validation errors returned by
// User.ValidateAll() if the designated constraints aren't met.
type UserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserMultiError) AllErrors() []error { return m }

// UserValidationError is the validation error returned by User.Validate if the
// designated constraints aren't met.
type UserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserValidationError) ErrorName() string { return "UserValidationError" }

// Error satisfies the builtin error interface
func (e UserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserValidationError{}

var _User_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _User_UserPassword_Pattern = regexp.MustCompile("^[\\x21-\\x7E]+$")

var _User_UserRole_NotInLookup = map[UserRoles]struct{}{
	0: {},
}

// Validate checks the field values on UserData with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UserData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserData with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UserDataMultiError, or nil
// if none found.
func (m *UserData) ValidateAll() error {
	return m.validate(true)
}

func (m *UserData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = UserDataValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserName()); l < 2 || l > 128 {
		err := UserDataValidationError{
			field:  "UserName",
			reason: "value length must be between 2 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_UserData_UserName_Pattern.MatchString(m.GetUserName()) {
		err := UserDataValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _UserData_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := UserDataValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := UserRoles_name[int32(m.GetUserRole())]; !ok {
		err := UserDataValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserDataMultiError(errors)
	}

	return nil
}

func (m *UserData) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// UserDataMultiError is an error wrapping multiple validation errors returned
// by UserData.ValidateAll() if the designated constraints aren't met.
type UserDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserDataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserDataMultiError) AllErrors() []error { return m }

// UserDataValidationError is the validation error returned by
// UserData.Validate if the designated constraints aren't met.
type UserDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserDataValidationError) ErrorName() string { return "UserDataValidationError" }

// Error satisfies the builtin error interface
func (e UserDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserDataValidationError{}

var _UserData_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _UserData_UserRole_NotInLookup = map[UserRoles]struct{}{
	0: {},
}

// Validate checks the field values on RegisterRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterRequestMultiError, or nil if none found.
func (m *RegisterRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetUserName()); l < 2 || l > 128 {
		err := RegisterRequestValidationError{
			field:  "UserName",
			reason: "value length must be between 2 and 128 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_RegisterRequest_UserName_Pattern.MatchString(m.GetUserName()) {
		err := RegisterRequestValidationError{
			field:  "UserName",
			reason: "value does not match regex pattern \"^[A-Za-z]+( [A-Za-z]+)*$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetUserPassword()); l < 8 || l > 72 {
		err := RegisterRequestValidationError{
			field:  "UserPassword",
			reason: "value length must be between 8 and 72 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if !_RegisterRequest_UserPassword_Pattern.MatchString(m.GetUserPassword()) {
		err := RegisterRequestValidationError{
			field:  "UserPassword",
			reason: "value does not match regex pattern \"^[\\\\x21-\\\\x7E]+$\"",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegisterRequestMultiError(errors)
	}

	return nil
}

// RegisterRequestMultiError is an error wrapping multiple validation errors
// returned by RegisterRequest.ValidateAll() if the designated constraints
// aren't met.
type RegisterRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterRequestMultiError) AllErrors() []error { return m }

// RegisterRequestValidationError is the validation error returned by
// RegisterRequest.Validate if the designated constraints aren't met.
type RegisterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterRequestValidationError) ErrorName() string { return "RegisterRequestValidationError" }

// Error satisfies the builtin error interface
func (e RegisterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterRequestValidationError{}

var _RegisterRequest_UserName_Pattern = regexp.MustCompile("^[A-Za-z]+( [A-Za-z]+)*$")

var _RegisterRequest_UserPassword_Pattern = regexp.MustCompile("^[\\x21-\\x7E]+$")

// Validate checks the field values on RegisterResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterResponseMultiError, or nil if none found.
func (m *RegisterResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserName

	if _, ok := _RegisterResponse_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := RegisterResponseValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := UserRoles_name[int32(m.GetUserRole())]; !ok {
		err := RegisterResponseValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RegisterResponseMultiError(errors)
	}

	return nil
}

// RegisterResponseMultiError is an error wrapping multiple validation errors
// returned by RegisterResponse.ValidateAll() if the designated constraints
// aren't met.
type RegisterResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterResponseMultiError) AllErrors() []error { return m }

// RegisterResponseValidationError is the validation error returned by
// RegisterResponse.Validate if the designated constraints aren't met.
type RegisterResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterResponseValidationError) ErrorName() string { return "RegisterResponseValidationError" }

// Error satisfies the builtin error interface
func (e RegisterResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterResponseValidationError{}

var _RegisterResponse_UserRole_NotInLookup = map[UserRoles]struct{}{
	0: {},
}

// Validate checks the field values on GetUserDataRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserDataRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserDataRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserDataRequestMultiError, or nil if none found.
func (m *GetUserDataRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserDataRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = GetUserDataRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetUserDataRequestMultiError(errors)
	}

	return nil
}

func (m *GetUserDataRequest) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// GetUserDataRequestMultiError is an error wrapping multiple validation errors
// returned by GetUserDataRequest.ValidateAll() if the designated constraints
// aren't met.
type GetUserDataRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserDataRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserDataRequestMultiError) AllErrors() []error { return m }

// GetUserDataRequestValidationError is the validation error returned by
// GetUserDataRequest.Validate if the designated constraints aren't met.
type GetUserDataRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserDataRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserDataRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserDataRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserDataRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserDataRequestValidationError) ErrorName() string {
	return "GetUserDataRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserDataRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserDataRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserDataRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserDataRequestValidationError{}

// Validate checks the field values on GetUserDataResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUserDataResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUserDataResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUserDataResponseMultiError, or nil if none found.
func (m *GetUserDataResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUserDataResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetUserData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetUserDataResponseValidationError{
					field:  "UserData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetUserDataResponseValidationError{
					field:  "UserData",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUserData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetUserDataResponseValidationError{
				field:  "UserData",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetUserDataResponseMultiError(errors)
	}

	return nil
}

// GetUserDataResponseMultiError is an error wrapping multiple validation
// errors returned by GetUserDataResponse.ValidateAll() if the designated
// constraints aren't met.
type GetUserDataResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUserDataResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUserDataResponseMultiError) AllErrors() []error { return m }

// GetUserDataResponseValidationError is the validation error returned by
// GetUserDataResponse.Validate if the designated constraints aren't met.
type GetUserDataResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUserDataResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUserDataResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUserDataResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUserDataResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUserDataResponseValidationError) ErrorName() string {
	return "GetUserDataResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetUserDataResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUserDataResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUserDataResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUserDataResponseValidationError{}

// Validate checks the field values on PlanChangeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PlanChangeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PlanChangeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PlanChangeRequestMultiError, or nil if none found.
func (m *PlanChangeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PlanChangeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = PlanChangeRequestValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _PlanChangeRequest_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := PlanChangeRequestValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := UserRoles_name[int32(m.GetUserRole())]; !ok {
		err := PlanChangeRequestValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PlanChangeRequestMultiError(errors)
	}

	return nil
}

func (m *PlanChangeRequest) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PlanChangeRequestMultiError is an error wrapping multiple validation errors
// returned by PlanChangeRequest.ValidateAll() if the designated constraints
// aren't met.
type PlanChangeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlanChangeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlanChangeRequestMultiError) AllErrors() []error { return m }

// PlanChangeRequestValidationError is the validation error returned by
// PlanChangeRequest.Validate if the designated constraints aren't met.
type PlanChangeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlanChangeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlanChangeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlanChangeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlanChangeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlanChangeRequestValidationError) ErrorName() string {
	return "PlanChangeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PlanChangeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlanChangeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlanChangeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlanChangeRequestValidationError{}

var _PlanChangeRequest_UserRole_NotInLookup = map[UserRoles]struct{}{
	0: {},
}

// Validate checks the field values on PlanChangeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PlanChangeResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PlanChangeResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PlanChangeResponseMultiError, or nil if none found.
func (m *PlanChangeResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *PlanChangeResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = PlanChangeResponseValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := _PlanChangeResponse_UserRole_NotInLookup[m.GetUserRole()]; ok {
		err := PlanChangeResponseValidationError{
			field:  "UserRole",
			reason: "value must not be in list [UNAUTHORISED_USER]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if _, ok := UserRoles_name[int32(m.GetUserRole())]; !ok {
		err := PlanChangeResponseValidationError{
			field:  "UserRole",
			reason: "value must be one of the defined enum values",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return PlanChangeResponseMultiError(errors)
	}

	return nil
}

func (m *PlanChangeResponse) _validateUuid(uuid string) error {
	if matched := _user_service_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// PlanChangeResponseMultiError is an error wrapping multiple validation errors
// returned by PlanChangeResponse.ValidateAll() if the designated constraints
// aren't met.
type PlanChangeResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PlanChangeResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PlanChangeResponseMultiError) AllErrors() []error { return m }

// PlanChangeResponseValidationError is the validation error returned by
// PlanChangeResponse.Validate if the designated constraints aren't met.
type PlanChangeResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PlanChangeResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PlanChangeResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PlanChangeResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PlanChangeResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PlanChangeResponseValidationError) ErrorName() string {
	return "PlanChangeResponseValidationError"
}

// Error satisfies the builtin error interface
func (e PlanChangeResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPlanChangeResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PlanChangeResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PlanChangeResponseValidationError{}

var _PlanChangeResponse_UserRole_NotInLookup = map[UserRoles]struct{}{
	0: {},
}
