// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: saga_events.proto

package saga_eventsPB

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_saga_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderCreated) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OrderCreated) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *OrderCreated) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderCreated) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *OrderCreated) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReserveStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReserveStock) Reset() {
	*x = ReserveStock{}
	mi := &file_saga_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStock) ProtoMessage() {}

func (x *ReserveStock) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStock.ProtoReflect.Descriptor instead.
func (*ReserveStock) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveStock) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStock) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveStock) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *ReserveStock) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type StockReserved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockReserved) Reset() {
	*x = StockReserved{}
	mi := &file_saga_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockReserved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockReserved) ProtoMessage() {}

func (x *StockReserved) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockReserved.ProtoReflect.Descriptor instead.
func (*StockReserved) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{2}
}

func (x *StockReserved) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockReserved) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

type StockRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	MarketId      string                 `protobuf:"bytes,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockRejected) Reset() {
	*x = StockRejected{}
	mi := &file_saga_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockRejected) ProtoMessage() {}

func (x *StockRejected) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockRejected.ProtoReflect.Descriptor instead.
func (*StockRejected) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{3}
}

func (x *StockRejected) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *StockRejected) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *StockRejected) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type OrderStatusChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusChanged) Reset() {
	*x = OrderStatusChanged{}
	mi := &file_saga_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusChanged) ProtoMessage() {}

func (x *OrderStatusChanged) ProtoReflect() protoreflect.Message {
	mi := &file_saga_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusChanged.ProtoReflect.Descriptor instead.
func (*OrderStatusChanged) Descriptor() ([]byte, []int) {
	return file_saga_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrderStatusChanged) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatusChanged) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_saga_events_proto protoreflect.FileDescriptor

const file_saga_events_proto_rawDesc = "" +
	"\n" +
	"\x11saga_events.proto\x12\x04saga\x1a\x1fproto_validation/validate.proto\"\xde\x01\n" +
	"\fOrderCreated\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12%\n" +
	"\tmarket_id\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\x12\x1d\n" +
	"\x05price\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05price\x12\x1f\n" +
	"\x06amount\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06amount\x12\x1f\n" +
	"\x06status\x18\x06 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06status\"\x9e\x01\n" +
	"\fReserveStock\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12!\n" +
	"\auser_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12%\n" +
	"\tmarket_id\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\x12\x1f\n" +
	"\x06amount\x18\x04 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06amount\"[\n" +
	"\rStockReserved\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12%\n" +
	"\tmarket_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\"s\n" +
	"\rStockRejected\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12%\n" +
	"\tmarket_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"Z\n" +
	"\x12OrderStatusChanged\x12#\n" +
	"\border_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\aorderId\x12\x1f\n" +
	"\x06status\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06statusB&Z$BHLA/proto/saga_events;saga_eventsPBb\x06proto3"

var (
	file_saga_events_proto_rawDescOnce sync.Once
	file_saga_events_proto_rawDescData []byte
)

func file_saga_events_proto_rawDescGZIP() []byte {
	file_saga_events_proto_rawDescOnce.Do(func() {
		file_saga_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_saga_events_proto_rawDesc), len(file_saga_events_proto_rawDesc)))
	})
	return file_saga_events_proto_rawDescData
}

var file_saga_events_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_saga_events_proto_goTypes = []any{
	(*OrderCreated)(nil),       // 0: saga.OrderCreated
	(*ReserveStock)(nil),       // 1: saga.ReserveStock
	(*StockReserved)(nil),      // 2: saga.StockReserved
	(*StockRejected)(nil),      // 3: saga.StockRejected
	(*OrderStatusChanged)(nil), // 4: saga.OrderStatusChanged
}
var file_saga_events_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_saga_events_proto_init() }
func file_saga_events_proto_init() {
	if File_saga_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_saga_events_proto_rawDesc), len(file_saga_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_saga_events_proto_goTypes,
		DependencyIndexes: file_saga_events_proto_depIdxs,
		MessageInfos:      file_saga_events_proto_msgTypes,
	}.Build()
	File_saga_events_proto = out.File
	file_saga_events_proto_goTypes = nil
	file_saga_events_proto_depIdxs = nil
}
