// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: saga_events.proto

package saga_eventsPB

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// define the regex for a UUID once up-front
var _saga_events_uuidPattern = regexp.MustCompile("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$")

// Validate checks the field values on OrderCreated with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OrderCreated) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderCreated with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OrderCreatedMultiError, or
// nil if none found.
func (m *OrderCreated) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderCreated) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOrderId()); err != nil {
		err = OrderCreatedValidationError{
			field:  "OrderId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = OrderCreatedValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetMarketId()); err != nil {
		err = OrderCreatedValidationError{
			field:  "MarketId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPrice()) < 1 {
		err := OrderCreatedValidationError{
			field:  "Price",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAmount()) < 1 {
		err := OrderCreatedValidationError{
			field:  "Amount",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetStatus()) < 1 {
		err := OrderCreatedValidationError{
			field:  "Status",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrderCreatedMultiError(errors)
	}

	return nil
}

func (m *OrderCreated) _validateUuid(uuid string) error {
	if matched := _saga_events_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OrderCreatedMultiError is an error wrapping multiple validation errors
// returned by OrderCreated.ValidateAll() if the designated constraints aren't met.
type OrderCreatedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderCreatedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderCreatedMultiError) AllErrors() []error { return m }

// OrderCreatedValidationError is the validation error returned by
// OrderCreated.Validate if the designated constraints aren't met.
type OrderCreatedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderCreatedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderCreatedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderCreatedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderCreatedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderCreatedValidationError) ErrorName() string { return "OrderCreatedValidationError" }

// Error satisfies the builtin error interface
func (e OrderCreatedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderCreated.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderCreatedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderCreatedValidationError{}

// Validate checks the field values on ReserveStock with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ReserveStock) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ReserveStock with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ReserveStockMultiError, or
// nil if none found.
func (m *ReserveStock) ValidateAll() error {
	return m.validate(true)
}

func (m *ReserveStock) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOrderId()); err != nil {
		err = ReserveStockValidationError{
			field:  "OrderId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetUserId()); err != nil {
		err = ReserveStockValidationError{
			field:  "UserId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetMarketId()); err != nil {
		err = ReserveStockValidationError{
			field:  "MarketId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetAmount()) < 1 {
		err := ReserveStockValidationError{
			field:  "Amount",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return ReserveStockMultiError(errors)
	}

	return nil
}

func (m *ReserveStock) _validateUuid(uuid string) error {
	if matched := _saga_events_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// ReserveStockMultiError is an error wrapping multiple validation errors
// returned by ReserveStock.ValidateAll() if the designated constraints aren't met.
type ReserveStockMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ReserveStockMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ReserveStockMultiError) AllErrors() []error { return m }

// ReserveStockValidationError is the validation error returned by
// ReserveStock.Validate if the designated constraints aren't met.
type ReserveStockValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ReserveStockValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ReserveStockValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ReserveStockValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ReserveStockValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ReserveStockValidationError) ErrorName() string { return "ReserveStockValidationError" }

// Error satisfies the builtin error interface
func (e ReserveStockValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sReserveStock.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ReserveStockValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ReserveStockValidationError{}

// Validate checks the field values on StockReserved with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StockReserved) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StockReserved with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StockReservedMultiError, or
// nil if none found.
func (m *StockReserved) ValidateAll() error {
	return m.validate(true)
}

func (m *StockReserved) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOrderId()); err != nil {
		err = StockReservedValidationError{
			field:  "OrderId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetMarketId()); err != nil {
		err = StockReservedValidationError{
			field:  "MarketId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return StockReservedMultiError(errors)
	}

	return nil
}

func (m *StockReserved) _validateUuid(uuid string) error {
	if matched := _saga_events_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// StockReservedMultiError is an error wrapping multiple validation errors
// returned by StockReserved.ValidateAll() if the designated constraints
// aren't met.
type StockReservedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StockReservedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StockReservedMultiError) AllErrors() []error { return m }

// StockReservedValidationError is the validation error returned by
// StockReserved.Validate if the designated constraints aren't met.
type StockReservedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StockReservedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StockReservedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StockReservedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StockReservedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StockReservedValidationError) ErrorName() string { return "StockReservedValidationError" }

// Error satisfies the builtin error interface
func (e StockReservedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStockReserved.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StockReservedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StockReservedValidationError{}

// Validate checks the field values on StockRejected with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *StockRejected) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on StockRejected with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in StockRejectedMultiError, or
// nil if none found.
func (m *StockRejected) ValidateAll() error {
	return m.validate(true)
}

func (m *StockRejected) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOrderId()); err != nil {
		err = StockRejectedValidationError{
			field:  "OrderId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if err := m._validateUuid(m.GetMarketId()); err != nil {
		err = StockRejectedValidationError{
			field:  "MarketId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Reason

	if len(errors) > 0 {
		return StockRejectedMultiError(errors)
	}

	return nil
}

func (m *StockRejected) _validateUuid(uuid string) error {
	if matched := _saga_events_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// StockRejectedMultiError is an error wrapping multiple validation errors
// returned by StockRejected.ValidateAll() if the designated constraints
// aren't met.
type StockRejectedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m StockRejectedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m StockRejectedMultiError) AllErrors() []error { return m }

// StockRejectedValidationError is the validation error returned by
// StockRejected.Validate if the designated constraints aren't met.
type StockRejectedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e StockRejectedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e StockRejectedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e StockRejectedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e StockRejectedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e StockRejectedValidationError) ErrorName() string { return "StockRejectedValidationError" }

// Error satisfies the builtin error interface
func (e StockRejectedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sStockRejected.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = StockRejectedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = StockRejectedValidationError{}

// Validate checks the field values on OrderStatusChanged with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *OrderStatusChanged) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OrderStatusChanged with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// OrderStatusChangedMultiError, or nil if none found.
func (m *OrderStatusChanged) ValidateAll() error {
	return m.validate(true)
}

func (m *OrderStatusChanged) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateUuid(m.GetOrderId()); err != nil {
		err = OrderStatusChangedValidationError{
			field:  "OrderId",
			reason: "value must be a valid UUID",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetStatus()) < 1 {
		err := OrderStatusChangedValidationError{
			field:  "Status",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return OrderStatusChangedMultiError(errors)
	}

	return nil
}

func (m *OrderStatusChanged) _validateUuid(uuid string) error {
	if matched := _saga_events_uuidPattern.MatchString(uuid); !matched {
		return errors.New("invalid uuid format")
	}

	return nil
}

// OrderStatusChangedMultiError is an error wrapping multiple validation errors
// returned by OrderStatusChanged.ValidateAll() if the designated constraints
// aren't met.
type OrderStatusChangedMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OrderStatusChangedMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OrderStatusChangedMultiError) AllErrors() []error { return m }

// OrderStatusChangedValidationError is the validation error returned by
// OrderStatusChanged.Validate if the designated constraints aren't met.
type OrderStatusChangedValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OrderStatusChangedValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OrderStatusChangedValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OrderStatusChangedValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OrderStatusChangedValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OrderStatusChangedValidationError) ErrorName() string {
	return "OrderStatusChangedValidationError"
}

// Error satisfies the builtin error interface
func (e OrderStatusChangedValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOrderStatusChanged.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OrderStatusChangedValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OrderStatusChangedValidationError{}
