// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: market_service.proto

package market_servicePB

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Market struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MarketName          string                 `protobuf:"bytes,1,opt,name=market_name,json=marketName,proto3" json:"market_name,omitempty"`
	GoodsId             string                 `protobuf:"bytes,2,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	MarketId            string                 `protobuf:"bytes,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	MarketAccessibility bool                   `protobuf:"varint,4,opt,name=market_accessibility,json=marketAccessibility,proto3" json:"market_accessibility,omitempty"`
	MarketTtl           int64                  `protobuf:"varint,5,opt,name=market_ttl,json=marketTtl,proto3" json:"market_ttl,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_market_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{0}
}

func (x *Market) GetMarketName() string {
	if x != nil {
		return x.MarketName
	}
	return ""
}

func (x *Market) GetGoodsId() string {
	if x != nil {
		return x.GoodsId
	}
	return ""
}

func (x *Market) GetMarketId() string {
	if x != nil {
		return x.MarketId
	}
	return ""
}

func (x *Market) GetMarketAccessibility() bool {
	if x != nil {
		return x.MarketAccessibility
	}
	return false
}

func (x *Market) GetMarketTtl() int64 {
	if x != nil {
		return x.MarketTtl
	}
	return 0
}

type ViewMarketRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ViewMarketRequest string                 `protobuf:"bytes,1,opt,name=view_market_request,json=viewMarketRequest,proto3" json:"view_market_request,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ViewMarketRequest) Reset() {
	*x = ViewMarketRequest{}
	mi := &file_market_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketRequest) ProtoMessage() {}

func (x *ViewMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketRequest.ProtoReflect.Descriptor instead.
func (*ViewMarketRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{1}
}

func (x *ViewMarketRequest) GetViewMarketRequest() string {
	if x != nil {
		return x.ViewMarketRequest
	}
	return ""
}

type ViewMarketResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ViewMarketResponse *Market                `protobuf:"bytes,1,opt,name=view_market_response,json=viewMarketResponse,proto3" json:"view_market_response,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ViewMarketResponse) Reset() {
	*x = ViewMarketResponse{}
	mi := &file_market_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewMarketResponse) ProtoMessage() {}

func (x *ViewMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewMarketResponse.ProtoReflect.Descriptor instead.
func (*ViewMarketResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{2}
}

func (x *ViewMarketResponse) GetViewMarketResponse() *Market {
	if x != nil {
		return x.ViewMarketResponse
	}
	return nil
}

type ViewAllMarketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAllMarketsRequest) Reset() {
	*x = ViewAllMarketsRequest{}
	mi := &file_market_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAllMarketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAllMarketsRequest) ProtoMessage() {}

func (x *ViewAllMarketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAllMarketsRequest.ProtoReflect.Descriptor instead.
func (*ViewAllMarketsRequest) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{3}
}

func (x *ViewAllMarketsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ViewAllMarketsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ViewAllMarketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Markets       []*Market              `protobuf:"bytes,1,rep,name=markets,proto3" json:"markets,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAllMarketsResponse) Reset() {
	*x = ViewAllMarketsResponse{}
	mi := &file_market_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAllMarketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAllMarketsResponse) ProtoMessage() {}

func (x *ViewAllMarketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAllMarketsResponse.ProtoReflect.Descriptor instead.
func (*ViewAllMarketsResponse) Descriptor() ([]byte, []int) {
	return file_market_service_proto_rawDescGZIP(), []int{4}
}

func (x *ViewAllMarketsResponse) GetMarkets() []*Market {
	if x != nil {
		return x.Markets
	}
	return nil
}

func (x *ViewAllMarketsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_market_service_proto protoreflect.FileDescriptor

const file_market_service_proto_rawDesc = "" +
	"\n" +
	"\x14market_service.proto\x12\x0emarket_service\x1a\x1fproto_validation/validate.proto\"\xd3\x01\n" +
	"\x06Market\x12+\n" +
	"\vmarket_name\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\x80\x02R\n" +
	"marketName\x12#\n" +
	"\bgoods_id\x18\x02 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\agoodsId\x12%\n" +
	"\tmarket_id\x18\x03 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\bmarketId\x121\n" +
	"\x14market_accessibility\x18\x04 \x01(\bR\x13marketAccessibility\x12\x1d\n" +
	"\n" +
	"market_ttl\x18\x05 \x01(\x03R\tmarketTtl\"O\n" +
	"\x11ViewMarketRequest\x12:\n" +
	"\x13view_market_request\x18\x01 \x01(\tB\n" +
	"\xfaB\ar\x05\x10\x02\x18\x80\x02R\x11viewMarketRequest\"^\n" +
	"\x12ViewMarketResponse\x12H\n" +
	"\x14view_market_response\x18\x01 \x01(\v2\x16.market_service.MarketR\x12viewMarketResponse\"S\n" +
	"\x15ViewAllMarketsRequest\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"r\n" +
	"\x16ViewAllMarketsResponse\x120\n" +
	"\amarkets\x18\x01 \x03(\v2\x16.market_service.MarketR\amarkets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xd2\x01\n" +
	"\x15SpotInstrumentService\x12X\n" +
	"\x0fViewMarketsByID\x12!.market_service.ViewMarketRequest\x1a\".market_service.ViewMarketResponse\x12_\n" +
	"\x0eViewAllMarkets\x12%.market_service.ViewAllMarketsRequest\x1a&.market_service.ViewAllMarketsResponseB,Z*BHLA/proto/market_service;market_servicePBb\x06proto3"

var (
	file_market_service_proto_rawDescOnce sync.Once
	file_market_service_proto_rawDescData []byte
)

func file_market_service_proto_rawDescGZIP() []byte {
	file_market_service_proto_rawDescOnce.Do(func() {
		file_market_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_service_proto_rawDesc), len(file_market_service_proto_rawDesc)))
	})
	return file_market_service_proto_rawDescData
}

var file_market_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_market_service_proto_goTypes = []any{
	(*Market)(nil),                 // 0: market_service.Market
	(*ViewMarketRequest)(nil),      // 1: market_service.ViewMarketRequest
	(*ViewMarketResponse)(nil),     // 2: market_service.ViewMarketResponse
	(*ViewAllMarketsRequest)(nil),  // 3: market_service.ViewAllMarketsRequest
	(*ViewAllMarketsResponse)(nil), // 4: market_service.ViewAllMarketsResponse
}
var file_market_service_proto_depIdxs = []int32{
	0, // 0: market_service.ViewMarketResponse.view_market_response:type_name -> market_service.Market
	0, // 1: market_service.ViewAllMarketsResponse.markets:type_name -> market_service.Market
	1, // 2: market_service.SpotInstrumentService.ViewMarketsByID:input_type -> market_service.ViewMarketRequest
	3, // 3: market_service.SpotInstrumentService.ViewAllMarkets:input_type -> market_service.ViewAllMarketsRequest
	2, // 4: market_service.SpotInstrumentService.ViewMarketsByID:output_type -> market_service.ViewMarketResponse
	4, // 5: market_service.SpotInstrumentService.ViewAllMarkets:output_type -> market_service.ViewAllMarketsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_market_service_proto_init() }
func file_market_service_proto_init() {
	if File_market_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_service_proto_rawDesc), len(file_market_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_service_proto_goTypes,
		DependencyIndexes: file_market_service_proto_depIdxs,
		MessageInfos:      file_market_service_proto_msgTypes,
	}.Build()
	File_market_service_proto = out.File
	file_market_service_proto_goTypes = nil
	file_market_service_proto_depIdxs = nil
}
