// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: user_service.proto

package user_servicePB

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRoles int32

const (
	UserRoles_UNAUTHORISED_USER UserRoles = 0
	UserRoles_FREE_PLAN_USER    UserRoles = 1
	UserRoles_PRO_PLAN_USER     UserRoles = 2
	UserRoles_ADMIN             UserRoles = 3
)

// Enum value maps for UserRoles.
var (
	UserRoles_name = map[int32]string{
		0: "UNAUTHORISED_USER",
		1: "FREE_PLAN_USER",
		2: "PRO_PLAN_USER",
		3: "ADMIN",
	}
	UserRoles_value = map[string]int32{
		"UNAUTHORISED_USER": 0,
		"FREE_PLAN_USER":    1,
		"PRO_PLAN_USER":     2,
		"ADMIN":             3,
	}
)

func (x UserRoles) Enum() *UserRoles {
	p := new(UserRoles)
	*p = x
	return p
}

func (x UserRoles) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRoles) Descriptor() protoreflect.EnumDescriptor {
	return file_user_service_proto_enumTypes[0].Descriptor()
}

func (UserRoles) Type() protoreflect.EnumType {
	return &file_user_service_proto_enumTypes[0]
}

func (x UserRoles) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRoles.Descriptor instead.
func (UserRoles) EnumDescriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword  string                 `protobuf:"bytes,3,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	UserRole      UserRoles              `protobuf:"varint,4,opt,name=user_role,json=userRole,proto3,enum=user_service.UserRoles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *User) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

func (x *User) GetUserRole() UserRoles {
	if x != nil {
		return x.UserRole
	}
	return UserRoles_UNAUTHORISED_USER
}

type UserData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserRole      UserRoles              `protobuf:"varint,3,opt,name=user_role,json=userRole,proto3,enum=user_service.UserRoles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserData) Reset() {
	*x = UserData{}
	mi := &file_user_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserData) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserData) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserData) GetUserRole() UserRoles {
	if x != nil {
		return x.UserRole
	}
	return UserRoles_UNAUTHORISED_USER
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserPassword  string                 `protobuf:"bytes,2,opt,name=user_password,json=userPassword,proto3" json:"user_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterRequest) GetUserPassword() string {
	if x != nil {
		return x.UserPassword
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserRole      UserRoles              `protobuf:"varint,2,opt,name=user_role,json=userRole,proto3,enum=user_service.UserRoles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *RegisterResponse) GetUserRole() UserRoles {
	if x != nil {
		return x.UserRole
	}
	return UserRoles_UNAUTHORISED_USER
}

type GetUserDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataRequest) Reset() {
	*x = GetUserDataRequest{}
	mi := &file_user_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataRequest) ProtoMessage() {}

func (x *GetUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataRequest.ProtoReflect.Descriptor instead.
func (*GetUserDataRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserDataRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      *UserData              `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserDataResponse) Reset() {
	*x = GetUserDataResponse{}
	mi := &file_user_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserDataResponse) ProtoMessage() {}

func (x *GetUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserDataResponse.ProtoReflect.Descriptor instead.
func (*GetUserDataResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserDataResponse) GetUserData() *UserData {
	if x != nil {
		return x.UserData
	}
	return nil
}

type PlanChangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRole      UserRoles              `protobuf:"varint,2,opt,name=user_role,json=userRole,proto3,enum=user_service.UserRoles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanChangeRequest) Reset() {
	*x = PlanChangeRequest{}
	mi := &file_user_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanChangeRequest) ProtoMessage() {}

func (x *PlanChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanChangeRequest.ProtoReflect.Descriptor instead.
func (*PlanChangeRequest) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{6}
}

func (x *PlanChangeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlanChangeRequest) GetUserRole() UserRoles {
	if x != nil {
		return x.UserRole
	}
	return UserRoles_UNAUTHORISED_USER
}

type PlanChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserRole      UserRoles              `protobuf:"varint,2,opt,name=user_role,json=userRole,proto3,enum=user_service.UserRoles" json:"user_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanChangeResponse) Reset() {
	*x = PlanChangeResponse{}
	mi := &file_user_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanChangeResponse) ProtoMessage() {}

func (x *PlanChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanChangeResponse.ProtoReflect.Descriptor instead.
func (*PlanChangeResponse) Descriptor() ([]byte, []int) {
	return file_user_service_proto_rawDescGZIP(), []int{7}
}

func (x *PlanChangeResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlanChangeResponse) GetUserRole() UserRoles {
	if x != nil {
		return x.UserRole
	}
	return UserRoles_UNAUTHORISED_USER
}

var File_user_service_proto protoreflect.FileDescriptor

const file_user_service_proto_rawDesc = "" +
	"\n" +
	"\x12user_service.proto\x12\fuser_service\x1a\x1fproto_validation/validate.proto\"\xee\x01\n" +
	"\x04User\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12A\n" +
	"\tuser_name\x18\x02 \x01(\tB$\xfaB!r\x1f\x10\x02\x18\x80\x012\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x12>\n" +
	"\ruser_password\x18\x03 \x01(\tB\x19\xfaB\x16r\x14\x10\b\x18H2\x0e^[\\x21-\\x7E]+$R\fuserPassword\x12@\n" +
	"\tuser_role\x18\x04 \x01(\x0e2\x17.user_service.UserRolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole\"\xb2\x01\n" +
	"\bUserData\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12A\n" +
	"\tuser_name\x18\x02 \x01(\tB$\xfaB!r\x1f\x10\x02\x18\x80\x012\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x12@\n" +
	"\tuser_role\x18\x03 \x01(\x0e2\x17.user_service.UserRolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole\"\x94\x01\n" +
	"\x0fRegisterRequest\x12A\n" +
	"\tuser_name\x18\x01 \x01(\tB$\xfaB!r\x1f\x10\x02\x18\x80\x012\x18^[A-Za-z]+( [A-Za-z]+)*$R\buserName\x12>\n" +
	"\ruser_password\x18\x02 \x01(\tB\x19\xfaB\x16r\x14\x10\b\x18H2\x0e^[\\x21-\\x7E]+$R\fuserPassword\"q\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12@\n" +
	"\tuser_role\x18\x02 \x01(\x0e2\x17.user_service.UserRolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole\"7\n" +
	"\x12GetUserDataRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\"J\n" +
	"\x13GetUserDataResponse\x123\n" +
	"\tuser_data\x18\x01 \x01(\v2\x16.user_service.UserDataR\buserData\"x\n" +
	"\x11PlanChangeRequest\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12@\n" +
	"\tuser_role\x18\x02 \x01(\x0e2\x17.user_service.UserRolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole\"y\n" +
	"\x12PlanChangeResponse\x12!\n" +
	"\auser_id\x18\x01 \x01(\tB\b\xfaB\x05r\x03\xb0\x01\x01R\x06userId\x12@\n" +
	"\tuser_role\x18\x02 \x01(\x0e2\x17.user_service.UserRolesB\n" +
	"\xfaB\a\x82\x01\x04\x10\x01 \x00R\buserRole*T\n" +
	"\tUserRoles\x12\x15\n" +
	"\x11UNAUTHORISED_USER\x10\x00\x12\x12\n" +
	"\x0eFREE_PLAN_USER\x10\x01\x12\x11\n" +
	"\rPRO_PLAN_USER\x10\x02\x12\t\n" +
	"\x05ADMIN\x10\x032\x89\x02\n" +
	"\vUserService\x12Q\n" +
	"\x10UserRegistration\x12\x1d.user_service.RegisterRequest\x1a\x1e.user_service.RegisterResponse\x12R\n" +
	"\vGetUserData\x12 .user_service.GetUserDataRequest\x1a!.user_service.GetUserDataResponse\x12S\n" +
	"\x0eChangeUserPlan\x12\x1f.user_service.PlanChangeRequest\x1a .user_service.PlanChangeResponseB(Z&BHLA/proto/user_service;user_servicePBb\x06proto3"

var (
	file_user_service_proto_rawDescOnce sync.Once
	file_user_service_proto_rawDescData []byte
)

func file_user_service_proto_rawDescGZIP() []byte {
	file_user_service_proto_rawDescOnce.Do(func() {
		file_user_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)))
	})
	return file_user_service_proto_rawDescData
}

var file_user_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_user_service_proto_goTypes = []any{
	(UserRoles)(0),              // 0: user_service.UserRoles
	(*User)(nil),                // 1: user_service.User
	(*UserData)(nil),            // 2: user_service.UserData
	(*RegisterRequest)(nil),     // 3: user_service.RegisterRequest
	(*RegisterResponse)(nil),    // 4: user_service.RegisterResponse
	(*GetUserDataRequest)(nil),  // 5: user_service.GetUserDataRequest
	(*GetUserDataResponse)(nil), // 6: user_service.GetUserDataResponse
	(*PlanChangeRequest)(nil),   // 7: user_service.PlanChangeRequest
	(*PlanChangeResponse)(nil),  // 8: user_service.PlanChangeResponse
}
var file_user_service_proto_depIdxs = []int32{
	0, // 0: user_service.User.user_role:type_name -> user_service.UserRoles
	0, // 1: user_service.UserData.user_role:type_name -> user_service.UserRoles
	0, // 2: user_service.RegisterResponse.user_role:type_name -> user_service.UserRoles
	2, // 3: user_service.GetUserDataResponse.user_data:type_name -> user_service.UserData
	0, // 4: user_service.PlanChangeRequest.user_role:type_name -> user_service.UserRoles
	0, // 5: user_service.PlanChangeResponse.user_role:type_name -> user_service.UserRoles
	3, // 6: user_service.UserService.UserRegistration:input_type -> user_service.RegisterRequest
	5, // 7: user_service.UserService.GetUserData:input_type -> user_service.GetUserDataRequest
	7, // 8: user_service.UserService.ChangeUserPlan:input_type -> user_service.PlanChangeRequest
	4, // 9: user_service.UserService.UserRegistration:output_type -> user_service.RegisterResponse
	6, // 10: user_service.UserService.GetUserData:output_type -> user_service.GetUserDataResponse
	8, // 11: user_service.UserService.ChangeUserPlan:output_type -> user_service.PlanChangeResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_user_service_proto_init() }
func file_user_service_proto_init() {
	if File_user_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_service_proto_rawDesc), len(file_user_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_service_proto_goTypes,
		DependencyIndexes: file_user_service_proto_depIdxs,
		EnumInfos:         file_user_service_proto_enumTypes,
		MessageInfos:      file_user_service_proto_msgTypes,
	}.Build()
	File_user_service_proto = out.File
	file_user_service_proto_goTypes = nil
	file_user_service_proto_depIdxs = nil
}
